version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "devsecops-poc"
    ARTIFACT_BUCKET: "devsecops-artifacts-dev"

phases:

  install:
    runtime-versions:
      nodejs: 18

    commands:
      - echo "Installing SonarScanner"
      - npm install -g sonarqube-scanner

      - echo "Installing Trivy"
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

      - echo "Installed Versions"
      - ./bin/trivy --version

  pre_build:
    commands:
      - echo "Preparing Build"
      - mkdir -p reports

      - export BUILD_ID=${CODEBUILD_BUILD_NUMBER}
      - export IMAGE_TAG=${CODEBUILD_BUILD_NUMBER}

      - export IMAGE_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}

      - echo "Logging into Amazon ECR"
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

      - echo "IMAGE_URI=${IMAGE_URI}"

      - echo "Testing SonarQube Connectivity"
      - curl -v ${SONAR_HOST_URL}/api/system/status

  build:
    commands:
      - echo "Installing Application Dependencies"

      - cd app
      - npm install

      - echo "Running Unit Tests"
      - npm test || true

      - cd ..

      - echo "Running SonarQube Analysis"

      - npx sonarqube-scanner -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.token=${SONAR_TOKEN} -Dsonar.projectKey=devsecops-poc -Dsonar.projectName="DevSecOps POC" -Dsonar.sources=app -Dsonar.exclusions=**/node_modules/**

      - echo "Building Docker Image"
      - docker build -t ${IMAGE_URI} ./app

      - echo "Running Trivy Image Scan"

      - ./bin/trivy image --severity HIGH,CRITICAL --format json -o reports/trivy-image.json ${IMAGE_URI}

      - echo "Generated Reports"
      - ls -lh reports

  post_build:
    commands:
      - echo "Uploading Security Reports"
      - aws s3 cp reports/ s3://${ARTIFACT_BUCKET}/security-reports/build-${BUILD_ID}/ --recursive

      - echo "Pushing Docker Image"
      - docker push ${IMAGE_URI}

      - echo "Generating ECS Artifact"

      - printf '[{"name":"devsecops-app","imageUri":"%s"}]' ${IMAGE_URI} > imagedefinitions.json

      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
