sonar.projectKey=devsecops-poc
sonar.projectName=DevSecOps POC

sonar.sources=.
sonar.tests=app/tests

sonar.test.inclusions=app/tests/**/*.js

sonar.exclusions=**/node_modules/**,**/coverage/**,**/reports/**,**/.git/**

sonar.javascript.lcov.reportPaths=app/coverage/lcov.info
